//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTopReplica {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnTopReplica.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnTopReplica.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset window completely?.
        /// </summary>
        internal static string AskReset {
            get {
                return ResourceManager.GetString("AskReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset
        ///All settings will be lost..
        /// </summary>
        internal static string AskResetButtonOk {
            get {
                return ResourceManager.GetString("AskResetButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can be used to reset all settings if you lost control over the window or moved it beyond the screen boundary..
        /// </summary>
        internal static string AskResetContent {
            get {
                return ResourceManager.GetString("AskResetContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string AskResetTitle {
            get {
                return ResourceManager.GetString("AskResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install OnTopReplica {0}?.
        /// </summary>
        internal static string AskUpdate {
            get {
                return ResourceManager.GetString("AskUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel update
        ///OnTopReplica will prompt you the next time it is started..
        /// </summary>
        internal static string AskUpdateButtonCancel {
            get {
                return ResourceManager.GetString("AskUpdateButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed
        ///Install OnTopReplica {0}..
        /// </summary>
        internal static string AskUpdateButtonOk {
            get {
                return ResourceManager.GetString("AskUpdateButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new version will be automatically downloaded and installed..
        /// </summary>
        internal static string AskUpdateContent {
            get {
                return ResourceManager.GetString("AskUpdateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed version: {0}
        ///Available version: {1}
        ///Download size: {2} bytes.
        /// </summary>
        internal static string AskUpdateExpanded {
            get {
                return ResourceManager.GetString("AskUpdateExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        internal static string AskUpdateTitle {
            get {
                return ResourceManager.GetString("AskUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by: Lorenz Cuno Klopfenstein..
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw regions using mouse..
        /// </summary>
        internal static string DrawRegions {
            get {
                return ResourceManager.GetString("DrawRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string ErrorDetailButton {
            get {
                return ResourceManager.GetString("ErrorDetailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details on Windows Aero.
        /// </summary>
        internal static string ErrorDetailsAero {
            get {
                return ResourceManager.GetString("ErrorDetailsAero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Aero is only available on Windows Vista Home Premium or higher..
        /// </summary>
        internal static string ErrorDetailsAeroInfo {
            get {
                return ResourceManager.GetString("ErrorDetailsAeroInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Desktop Composition&apos; is not enabled..
        /// </summary>
        internal static string ErrorDwmOff {
            get {
                return ResourceManager.GetString("ErrorDwmOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enable desktop composition, by selecting &apos;Windows Aero&apos; as the theme used by Windows.
        ///
        ///To do so, right-click on the desktop and click on Personalize..
        /// </summary>
        internal static string ErrorDwmOffContent {
            get {
                return ResourceManager.GetString("ErrorDwmOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error details.
        /// </summary>
        internal static string ErrorGenericInfoButton {
            get {
                return ResourceManager.GetString("ErrorGenericInfoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string ErrorGenericInfoText {
            get {
                return ResourceManager.GetString("ErrorGenericInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears that the selected window has been closed or is not valid anymore..
        /// </summary>
        internal static string ErrorGenericThumbnailHandleError {
            get {
                return ResourceManager.GetString("ErrorGenericThumbnailHandleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorGenericTitle {
            get {
                return ResourceManager.GetString("ErrorGenericTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Desktop Composition&apos; is not supported on your Operating System.
        ///You must run this application on Windows Vista Home Premium or better..
        /// </summary>
        internal static string ErrorNoDwm {
            get {
                return ResourceManager.GetString("ErrorNoDwm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Composition unsupported.
        /// </summary>
        internal static string ErrorNoDwmTitle {
            get {
                return ResourceManager.GetString("ErrorNoDwmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No thumbnail loaded..
        /// </summary>
        internal static string ErrorNoThumbnail {
            get {
                return ResourceManager.GetString("ErrorNoThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create thumbnail..
        /// </summary>
        internal static string ErrorUnableToCreateThumbnail {
            get {
                return ResourceManager.GetString("ErrorUnableToCreateThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fit window..
        /// </summary>
        internal static string ErrorUnableToFit {
            get {
                return ResourceManager.GetString("ErrorUnableToFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to check for updates..
        /// </summary>
        internal static string ErrorUpdate {
            get {
                return ResourceManager.GetString("ErrorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears that OnTopReplica wasn&apos;t installed using &apos;ClickOnce&apos;. You&apos;ll have to update manually (visit &lt;a href=&quot;http://www.codeplex.com/ontopreplica&quot;&gt;OnTopReplica&apos;s homepage&lt;/a&gt;)..
        /// </summary>
        internal static string ErrorUpdateContent {
            get {
                return ResourceManager.GetString("ErrorUpdateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage: www.codeplex.com/ontopreplica..
        /// </summary>
        internal static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to enable &quot;click forwarding&quot;?.
        /// </summary>
        internal static string InfoClickForwarding {
            get {
                return ResourceManager.GetString("InfoClickForwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this mode OnTopReplica will forward all left mouse clicks on it to the window that is being clones (this will allow you to do basic operations on the window without having to activate it).
        ///
        ///To exit this mode, right-click on OnTopReplica and disable &quot;Click forwarding&quot; from the menu..
        /// </summary>
        internal static string InfoClickForwardingContent {
            get {
                return ResourceManager.GetString("InfoClickForwardingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click forwarding.
        /// </summary>
        internal static string InfoClickForwardingTitle {
            get {
                return ResourceManager.GetString("InfoClickForwardingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Click-Through fullscreen mode?.
        /// </summary>
        internal static string InfoClickThrough {
            get {
                return ResourceManager.GetString("InfoClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click-through only works if it has been enabled in the Resize submenu and if the window is semi-transparent..
        /// </summary>
        internal static string InfoClickThroughDetails {
            get {
                return ResourceManager.GetString("InfoClickThroughDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this mode the fullscreen window will behave as a partially transparent overlay, allowing you to click on the other windows behind it.
        ///
        ///To return to normal mode anytime, double click on the OnTopReplica icon in the tray area..
        /// </summary>
        internal static string InfoClickThroughInformation {
            get {
                return ResourceManager.GetString("InfoClickThroughInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, use standard fullscreen
        ///You can enable click-through later.
        /// </summary>
        internal static string InfoClickThroughNo {
            get {
                return ResourceManager.GetString("InfoClickThroughNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Click-Through.
        /// </summary>
        internal static string InfoClickThroughOk {
            get {
                return ResourceManager.GetString("InfoClickThroughOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click-Through mode.
        /// </summary>
        internal static string InfoClickThroughTitle {
            get {
                return ResourceManager.GetString("InfoClickThroughTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnTopReplica has been updated..
        /// </summary>
        internal static string InfoUpdated {
            get {
                return ResourceManager.GetString("InfoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to use the updated version of OnTopReplica you&apos;ll have to restart the application..
        /// </summary>
        internal static string InfoUpdatedContent {
            get {
                return ResourceManager.GetString("InfoUpdatedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successful.
        /// </summary>
        internal static string InfoUpdatedTitle {
            get {
                return ResourceManager.GetString("InfoUpdatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnTopReplica is up to date..
        /// </summary>
        internal static string InfoUpToDate {
            get {
                return ResourceManager.GetString("InfoUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update available.
        /// </summary>
        internal static string InfoUpToDateTitle {
            get {
                return ResourceManager.GetString("InfoUpToDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hides the main window and displays the &quot;about&quot; box..
        /// </summary>
        internal static string MenuAboutTT {
            get {
                return ResourceManager.GetString("MenuAboutTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autofit on resize.
        /// </summary>
        internal static string MenuAutofit {
            get {
                return ResourceManager.GetString("MenuAutofit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically fits the window to the thumbnail when you resize it..
        /// </summary>
        internal static string MenuAutofitTT {
            get {
                return ResourceManager.GetString("MenuAutofitTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click forwarding.
        /// </summary>
        internal static string MenuClickForwarding {
            get {
                return ResourceManager.GetString("MenuClickForwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable &quot;click forwarding&quot; to the cloned window..
        /// </summary>
        internal static string MenuClickForwardingTT {
            get {
                return ResourceManager.GetString("MenuClickForwardingTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string MenuClose {
            get {
                return ResourceManager.GetString("MenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes OnTopReplica..
        /// </summary>
        internal static string MenuCloseTT {
            get {
                return ResourceManager.GetString("MenuCloseTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2:1 Double.
        /// </summary>
        internal static string MenuFitDouble {
            get {
                return ResourceManager.GetString("MenuFitDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        internal static string MenuFitFullscreen {
            get {
                return ResourceManager.GetString("MenuFitFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1:2 Half.
        /// </summary>
        internal static string MenuFitHalf {
            get {
                return ResourceManager.GetString("MenuFitHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1:1 Fit to window.
        /// </summary>
        internal static string MenuFitOriginal {
            get {
                return ResourceManager.GetString("MenuFitOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1:4 Quarter.
        /// </summary>
        internal static string MenuFitQuarter {
            get {
                return ResourceManager.GetString("MenuFitQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass.
        /// </summary>
        internal static string MenuGlass {
            get {
                return ResourceManager.GetString("MenuGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles &quot;glass mode&quot; on and off..
        /// </summary>
        internal static string MenuGlassTT {
            get {
                return ResourceManager.GetString("MenuGlassTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% (opaque).
        /// </summary>
        internal static string MenuOp100 {
            get {
                return ResourceManager.GetString("MenuOp100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets OnTopReplica to be completely opaque..
        /// </summary>
        internal static string MenuOp100TT {
            get {
                return ResourceManager.GetString("MenuOp100TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25%.
        /// </summary>
        internal static string MenuOp25 {
            get {
                return ResourceManager.GetString("MenuOp25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets OnTopReplica to 25% opacity..
        /// </summary>
        internal static string MenuOp25TT {
            get {
                return ResourceManager.GetString("MenuOp25TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50%.
        /// </summary>
        internal static string MenuOp50 {
            get {
                return ResourceManager.GetString("MenuOp50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets OnTopReplica to 50% opacity..
        /// </summary>
        internal static string MenuOp50TT {
            get {
                return ResourceManager.GetString("MenuOp50TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75%.
        /// </summary>
        internal static string MenuOp75 {
            get {
                return ResourceManager.GetString("MenuOp75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets OnTopReplica to 75% opacity..
        /// </summary>
        internal static string MenuOp75TT {
            get {
                return ResourceManager.GetString("MenuOp75TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string MenuOpacity {
            get {
                return ResourceManager.GetString("MenuOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays OnTopReplica..
        /// </summary>
        internal static string MenuOpenTT {
            get {
                return ResourceManager.GetString("MenuOpenTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Left.
        /// </summary>
        internal static string MenuPosBottomLeft {
            get {
                return ResourceManager.GetString("MenuPosBottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Right.
        /// </summary>
        internal static string MenuPosBottomRight {
            get {
                return ResourceManager.GetString("MenuPosBottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string MenuPosition {
            get {
                return ResourceManager.GetString("MenuPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically position OnTopReplica on the current screen..
        /// </summary>
        internal static string MenuPositionTT {
            get {
                return ResourceManager.GetString("MenuPositionTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Left.
        /// </summary>
        internal static string MenuPosTopLeft {
            get {
                return ResourceManager.GetString("MenuPosTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Right.
        /// </summary>
        internal static string MenuPosTopRight {
            get {
                return ResourceManager.GetString("MenuPosTopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit fullscreen mode.
        /// </summary>
        internal static string MenuQuitFullscreen {
            get {
                return ResourceManager.GetString("MenuQuitFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recall last position and size.
        /// </summary>
        internal static string MenuRecall {
            get {
                return ResourceManager.GetString("MenuRecall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles whether OnTopReplica should store its last position and size and use them when it is restarted..
        /// </summary>
        internal static string MenuRecallTT {
            get {
                return ResourceManager.GetString("MenuRecallTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce to icon.
        /// </summary>
        internal static string MenuReduce {
            get {
                return ResourceManager.GetString("MenuReduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduces OnTopReplica to the icon in the tray..
        /// </summary>
        internal static string MenuReduceTT {
            get {
                return ResourceManager.GetString("MenuReduceTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select region....
        /// </summary>
        internal static string MenuRegion {
            get {
                return ResourceManager.GetString("MenuRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switches to &quot;region mode&quot;, that allows you to select a limited region of the source&apos;s window as thumbnail..
        /// </summary>
        internal static string MenuRegionTT {
            get {
                return ResourceManager.GetString("MenuRegionTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset window.
        /// </summary>
        internal static string MenuReset {
            get {
                return ResourceManager.GetString("MenuReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets OnTopReplica settings and its main window..
        /// </summary>
        internal static string MenuResetTT {
            get {
                return ResourceManager.GetString("MenuResetTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        internal static string MenuResize {
            get {
                return ResourceManager.GetString("MenuResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click-Through.
        /// </summary>
        internal static string MenuResizeClickThrough {
            get {
                return ResourceManager.GetString("MenuResizeClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the window is not completely opaque when turned to fullscreen mode, it will let all clicks &quot;fall through&quot; (like a transparent overlay)..
        /// </summary>
        internal static string MenuResizeClickThroughTT {
            get {
                return ResourceManager.GetString("MenuResizeClickThroughTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to window.
        /// </summary>
        internal static string MenuSwitch {
            get {
                return ResourceManager.GetString("MenuSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switches to the source window and hides OnTopReplica..
        /// </summary>
        internal static string MenuSwitchTT {
            get {
                return ResourceManager.GetString("MenuSwitchTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select window.
        /// </summary>
        internal static string MenuWindows {
            get {
                return ResourceManager.GetString("MenuWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - none -.
        /// </summary>
        internal static string MenuWindowsNone {
            get {
                return ResourceManager.GetString("MenuWindowsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a list of window you can select as thumbnail source..
        /// </summary>
        internal static string MenuWindowsTT {
            get {
                return ResourceManager.GetString("MenuWindowsTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current region:.
        /// </summary>
        internal static string RegionsCurrentRegion {
            get {
                return ResourceManager.GetString("RegionsCurrentRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string RegionsDeleteButton {
            get {
                return ResourceManager.GetString("RegionsDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string RegionsDoneButton {
            get {
                return ResourceManager.GetString("RegionsDoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string RegionsHeight {
            get {
                return ResourceManager.GetString("RegionsHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string RegionsResetButton {
            get {
                return ResourceManager.GetString("RegionsResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string RegionsSaveButton {
            get {
                return ResourceManager.GetString("RegionsSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored regions.
        /// </summary>
        internal static string RegionsStoredRegions {
            get {
                return ResourceManager.GetString("RegionsStoredRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        internal static string RegionsTitle {
            get {
                return ResourceManager.GetString("RegionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string RegionsWidth {
            get {
                return ResourceManager.GetString("RegionsWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-click here to start....
        /// </summary>
        internal static string RightClick {
            get {
                return ResourceManager.GetString("RightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lightweight, real-time, always on top thumbnail of a window of your choice..
        /// </summary>
        internal static string Slogan {
            get {
                return ResourceManager.GetString("Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnTopReplica automatically checks for updates. No information is logged at any point..
        /// </summary>
        internal static string UpdateDisclaimer {
            get {
                return ResourceManager.GetString("UpdateDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update now!.
        /// </summary>
        internal static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
    }
}
