//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTopReplica {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnTopReplica.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Created by: %. 的當地語系化字串。
        /// </summary>
        internal static string AboutAuthor {
            get {
                return ResourceManager.GetString("AboutAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Lorenz Cuno Klopfenstein 的當地語系化字串。
        /// </summary>
        internal static string AboutAuthorContent {
            get {
                return ResourceManager.GetString("AboutAuthorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Abort update process. 的當地語系化字串。
        /// </summary>
        internal static string AboutButtonCancelTT {
            get {
                return ResourceManager.GetString("AboutButtonCancelTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show details about OnTopReplica. 的當地語系化字串。
        /// </summary>
        internal static string AboutButtonExpanderTT {
            get {
                return ResourceManager.GetString("AboutButtonExpanderTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reset all OnTopReplica settings. 的當地語系化字串。
        /// </summary>
        internal static string AboutButtonResetTT {
            get {
                return ResourceManager.GetString("AboutButtonResetTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update OnTopReplica now. 的當地語系化字串。
        /// </summary>
        internal static string AboutButtonUpdateTT {
            get {
                return ResourceManager.GetString("AboutButtonUpdateTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Care to contribute to the project? You are welcome to improve available translations, start a new one for your native language or to check out the % from CodePlex. 的當地語系化字串。
        /// </summary>
        internal static string AboutContribute {
            get {
                return ResourceManager.GetString("AboutContribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 source code 的當地語系化字串。
        /// </summary>
        internal static string AboutContributeContent {
            get {
                return ResourceManager.GetString("AboutContributeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OnTopReplica is based upon the WindowsFormsAero library and some other libraries and code sources. %. 的當地語系化字串。
        /// </summary>
        internal static string AboutCreditsSources {
            get {
                return ResourceManager.GetString("AboutCreditsSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Read the full credits 的當地語系化字串。
        /// </summary>
        internal static string AboutCreditsSourcesContent {
            get {
                return ResourceManager.GetString("AboutCreditsSourcesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Contribute 的當地語系化字串。
        /// </summary>
        internal static string AboutDividerContribute {
            get {
                return ResourceManager.GetString("AboutDividerContribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Credits 的當地語系化字串。
        /// </summary>
        internal static string AboutDividerCredits {
            get {
                return ResourceManager.GetString("AboutDividerCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 License 的當地語系化字串。
        /// </summary>
        internal static string AboutDividerLicense {
            get {
                return ResourceManager.GetString("AboutDividerLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Updates 的當地語系化字串。
        /// </summary>
        internal static string AboutDividerUpdates {
            get {
                return ResourceManager.GetString("AboutDividerUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The application is licensed under the % license, which meets the terms of the &quot;open-source&quot; definition specified by OSI. 的當地語系化字串。
        /// </summary>
        internal static string AboutLicense {
            get {
                return ResourceManager.GetString("AboutLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Microsoft Reciprocal (MS-RL) 的當地語系化字串。
        /// </summary>
        internal static string AboutLicenseContent {
            get {
                return ResourceManager.GetString("AboutLicenseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 A lightweight, real-time, always on top thumbnail of a window of your choice. 的當地語系化字串。
        /// </summary>
        internal static string AboutSlogan {
            get {
                return ResourceManager.GetString("AboutSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 About OnTopReplica 的當地語系化字串。
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Translators: {0} 的當地語系化字串。
        /// </summary>
        internal static string AboutTranslators {
            get {
                return ResourceManager.GetString("AboutTranslators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Christian Olaechea M., Daniel Zeus.EX, Federico Lorenzo, Goran Brecelj, Jan Romanczyk, Marco Kraxner, Patrik (batupata), Raúl Morillo, René Mihula, Roberto Leiro, Rodrigo Lourenço, Thomas Amundsen, Eric Hoffmann. 的當地語系化字串。
        /// </summary>
        internal static string AboutTranslatorsContent {
            get {
                return ResourceManager.GetString("AboutTranslatorsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Check now! 的當地語系化字串。
        /// </summary>
        internal static string AboutUpdatesCheckNow {
            get {
                return ResourceManager.GetString("AboutUpdatesCheckNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OnTopReplica automatically checks for updates at every start up. 的當地語系化字串。
        /// </summary>
        internal static string AboutUpdatesDisclaimer {
            get {
                return ResourceManager.GetString("AboutUpdatesDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Version {0} 的當地語系化字串。
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OnTopReplica 的當地語系化字串。
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reset window completely? 的當地語系化字串。
        /// </summary>
        internal static string AskReset {
            get {
                return ResourceManager.GetString("AskReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;Reset
        ///All settings will be lost. 的當地語系化字串。
        /// </summary>
        internal static string AskResetButtonOk {
            get {
                return ResourceManager.GetString("AskResetButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Can be used to reset all settings if you lost control over the window or moved it beyond the screen boundary. 的當地語系化字串。
        /// </summary>
        internal static string AskResetContent {
            get {
                return ResourceManager.GetString("AskResetContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reset 的當地語系化字串。
        /// </summary>
        internal static string AskResetTitle {
            get {
                return ResourceManager.GetString("AskResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reset settings? 的當地語系化字串。
        /// </summary>
        internal static string AskSettingReset {
            get {
                return ResourceManager.GetString("AskSettingReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This will erase all settings of OnTopReplica, returning it to the original state right after installation (all saved information, like stored regions, will be lost). 的當地語系化字串。
        /// </summary>
        internal static string AskSettingResetContent {
            get {
                return ResourceManager.GetString("AskSettingResetContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reset settings 的當地語系化字串。
        /// </summary>
        internal static string AskSettingResetTitle {
            get {
                return ResourceManager.GetString("AskSettingResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;Cancel 的當地語系化字串。
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Draw regions using mouse. 的當地語系化字串。
        /// </summary>
        internal static string DrawRegions {
            get {
                return ResourceManager.GetString("DrawRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Details 的當地語系化字串。
        /// </summary>
        internal static string ErrorDetailButton {
            get {
                return ResourceManager.GetString("ErrorDetailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Details on Windows Aero 的當地語系化字串。
        /// </summary>
        internal static string ErrorDetailsAero {
            get {
                return ResourceManager.GetString("ErrorDetailsAero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Windows Aero is only available on Windows Vista Home Premium or higher. 的當地語系化字串。
        /// </summary>
        internal static string ErrorDetailsAeroInfo {
            get {
                return ResourceManager.GetString("ErrorDetailsAeroInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &apos;Desktop Composition&apos; is not enabled. 的當地語系化字串。
        /// </summary>
        internal static string ErrorDwmOff {
            get {
                return ResourceManager.GetString("ErrorDwmOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You must enable desktop composition, by selecting &apos;Windows Aero&apos; as the theme used by Windows.
        ///
        ///To do so, right-click on the desktop and click on Personalize. 的當地語系化字串。
        /// </summary>
        internal static string ErrorDwmOffContent {
            get {
                return ResourceManager.GetString("ErrorDwmOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error details 的當地語系化字串。
        /// </summary>
        internal static string ErrorGenericInfoButton {
            get {
                return ResourceManager.GetString("ErrorGenericInfoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error:  的當地語系化字串。
        /// </summary>
        internal static string ErrorGenericInfoText {
            get {
                return ResourceManager.GetString("ErrorGenericInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 It appears that the selected window has been closed or is not valid anymore. 的當地語系化字串。
        /// </summary>
        internal static string ErrorGenericThumbnailHandleError {
            get {
                return ResourceManager.GetString("ErrorGenericThumbnailHandleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error 的當地語系化字串。
        /// </summary>
        internal static string ErrorGenericTitle {
            get {
                return ResourceManager.GetString("ErrorGenericTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Desktop Composition&apos; is not supported on your Operating System.
        ///You must run this application on Windows Vista Home Premium or better. 的當地語系化字串。
        /// </summary>
        internal static string ErrorNoDwm {
            get {
                return ResourceManager.GetString("ErrorNoDwm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Desktop Composition unsupported 的當地語系化字串。
        /// </summary>
        internal static string ErrorNoDwmTitle {
            get {
                return ResourceManager.GetString("ErrorNoDwmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No thumbnail loaded. 的當地語系化字串。
        /// </summary>
        internal static string ErrorNoThumbnail {
            get {
                return ResourceManager.GetString("ErrorNoThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unable to create thumbnail 的當地語系化字串。
        /// </summary>
        internal static string ErrorUnableToCreateThumbnail {
            get {
                return ResourceManager.GetString("ErrorUnableToCreateThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unable to fit window. 的當地語系化字串。
        /// </summary>
        internal static string ErrorUnableToFit {
            get {
                return ResourceManager.GetString("ErrorUnableToFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unable to check for updates. 的當地語系化字串。
        /// </summary>
        internal static string ErrorUpdate {
            get {
                return ResourceManager.GetString("ErrorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 It appears that OnTopReplica wasn&apos;t installed using &apos;ClickOnce&apos;. You&apos;ll have to update manually (visit &lt;a href=&quot;http://ontopreplica.codeplex.com&quot;&gt;OnTopReplica&apos;s homepage&lt;/a&gt;). 的當地語系化字串。
        /// </summary>
        internal static string ErrorUpdateContent {
            get {
                return ResourceManager.GetString("ErrorUpdateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OnTopReplica was unable to check whether an updated version is available. Make sure you are connected to the Internet. If you are, the website may be temporarily down. 的當地語系化字串。
        /// </summary>
        internal static string ErrorUpdateContentGeneric {
            get {
                return ResourceManager.GetString("ErrorUpdateContentGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Mode 的當地語系化字串。
        /// </summary>
        internal static string FullscreenMode {
            get {
                return ResourceManager.GetString("FullscreenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Always on top 的當地語系化字串。
        /// </summary>
        internal static string FullscreenModeAlwaysOnTop {
            get {
                return ResourceManager.GetString("FullscreenModeAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Forces OnTopReplica to stay always on top. 的當地語系化字串。
        /// </summary>
        internal static string FullscreenModeAlwaysOnTopTT {
            get {
                return ResourceManager.GetString("FullscreenModeAlwaysOnTopTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Click through 的當地語系化字串。
        /// </summary>
        internal static string FullscreenModeClickThrough {
            get {
                return ResourceManager.GetString("FullscreenModeClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OnTopReplica will behave like a transparent overlay that lets your clicks through to the windows below. 的當地語系化字串。
        /// </summary>
        internal static string FullscreenModeClickThroughTT {
            get {
                return ResourceManager.GetString("FullscreenModeClickThroughTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Standard 的當地語系化字串。
        /// </summary>
        internal static string FullscreenModeNormal {
            get {
                return ResourceManager.GetString("FullscreenModeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Behaves like an ordinary window. You can bring other windows above OnTopReplica. 的當地語系化字串。
        /// </summary>
        internal static string FullscreenModeNormalTT {
            get {
                return ResourceManager.GetString("FullscreenModeNormalTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OnTopReplica fullscreen 的當地語系化字串。
        /// </summary>
        internal static string FullscreenTitle {
            get {
                return ResourceManager.GetString("FullscreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Disable 的當地語系化字串。
        /// </summary>
        internal static string GroupSwitchModeDisableButton {
            get {
                return ResourceManager.GetString("GroupSwitchModeDisableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable Group mode 的當地語系化字串。
        /// </summary>
        internal static string GroupSwitchModeEnableButton {
            get {
                return ResourceManager.GetString("GroupSwitchModeEnableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select multiple windows to enable. 的當地語系化字串。
        /// </summary>
        internal static string GroupSwitchModeStatusDisabled {
            get {
                return ResourceManager.GetString("GroupSwitchModeStatusDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Group switch mode is enabled. 的當地語系化字串。
        /// </summary>
        internal static string GroupSwitchModeStatusEnabled {
            get {
                return ResourceManager.GetString("GroupSwitchModeStatusEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Group switch mode: 的當地語系化字串。
        /// </summary>
        internal static string GroupSwitchModeTitle {
            get {
                return ResourceManager.GetString("GroupSwitchModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Windows 的當地語系化字串。
        /// </summary>
        internal static string GroupSwitchModeWindows {
            get {
                return ResourceManager.GetString("GroupSwitchModeWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Homepage: www.codeplex.com/ontopreplica. 的當地語系化字串。
        /// </summary>
        internal static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Do you want to enable &quot;click forwarding&quot;? 的當地語系化字串。
        /// </summary>
        internal static string InfoClickForwarding {
            get {
                return ResourceManager.GetString("InfoClickForwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If this mode is enabled, OnTopReplica will forward all left mouse clicks to the window that is being cloned (this will allow you to do basic mouse operations on the cloned window without having to activate it).
        ///
        ///To exit this mode, push ESC. 的當地語系化字串。
        /// </summary>
        internal static string InfoClickForwardingContent {
            get {
                return ResourceManager.GetString("InfoClickForwardingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Click forwarding 的當地語系化字串。
        /// </summary>
        internal static string InfoClickForwardingTitle {
            get {
                return ResourceManager.GetString("InfoClickForwardingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable Click-Through mode? 的當地語系化字串。
        /// </summary>
        internal static string InfoClickThrough {
            get {
                return ResourceManager.GetString("InfoClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Click-through only works if it has been enabled in the Resize submenu and if the window is semi-transparent. 的當地語系化字串。
        /// </summary>
        internal static string InfoClickThroughDetails {
            get {
                return ResourceManager.GetString("InfoClickThroughDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 In this mode the fullscreen window will behave as a partially transparent overlay, allowing you to click on the other windows behind it.
        ///
        ///To return to normal mode anytime, activate OnTopReplica by clicking on the task bar (or the tray icon). 的當地語系化字串。
        /// </summary>
        internal static string InfoClickThroughInformation {
            get {
                return ResourceManager.GetString("InfoClickThroughInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No, thank you.
        ///You can enable click-through later 的當地語系化字串。
        /// </summary>
        internal static string InfoClickThroughNo {
            get {
                return ResourceManager.GetString("InfoClickThroughNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use Click-Through 的當地語系化字串。
        /// </summary>
        internal static string InfoClickThroughOk {
            get {
                return ResourceManager.GetString("InfoClickThroughOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Click-Through mode 的當地語系化字串。
        /// </summary>
        internal static string InfoClickThroughTitle {
            get {
                return ResourceManager.GetString("InfoClickThroughTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OnTopReplica has been updated. 的當地語系化字串。
        /// </summary>
        internal static string InfoUpdated {
            get {
                return ResourceManager.GetString("InfoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 In order to use the updated version of OnTopReplica you&apos;ll have to restart the application. 的當地語系化字串。
        /// </summary>
        internal static string InfoUpdatedContent {
            get {
                return ResourceManager.GetString("InfoUpdatedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update successful 的當地語系化字串。
        /// </summary>
        internal static string InfoUpdatedTitle {
            get {
                return ResourceManager.GetString("InfoUpdatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OnTopReplica is up to date. 的當地語系化字串。
        /// </summary>
        internal static string InfoUpToDate {
            get {
                return ResourceManager.GetString("InfoUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No update available 的當地語系化字串。
        /// </summary>
        internal static string InfoUpToDateTitle {
            get {
                return ResourceManager.GetString("InfoUpToDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Language 的當地語系化字串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 About... 的當地語系化字串。
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hides the main window and displays the &quot;about&quot; box. 的當地語系化字串。
        /// </summary>
        internal static string MenuAboutTT {
            get {
                return ResourceManager.GetString("MenuAboutTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Advanced 的當地語系化字串。
        /// </summary>
        internal static string MenuAdvanced {
            get {
                return ResourceManager.GetString("MenuAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show window border 的當地語系化字串。
        /// </summary>
        internal static string MenuChrome {
            get {
                return ResourceManager.GetString("MenuChrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Toggles the display of the window border. 的當地語系化字串。
        /// </summary>
        internal static string MenuChromeTT {
            get {
                return ResourceManager.GetString("MenuChromeTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable Click forwarding 的當地語系化字串。
        /// </summary>
        internal static string MenuClickForwarding {
            get {
                return ResourceManager.GetString("MenuClickForwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable &quot;click forwarding&quot; to the cloned window. 的當地語系化字串。
        /// </summary>
        internal static string MenuClickForwardingTT {
            get {
                return ResourceManager.GetString("MenuClickForwardingTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable Click-Through 的當地語系化字串。
        /// </summary>
        internal static string MenuClickThrough {
            get {
                return ResourceManager.GetString("MenuClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OnTopReplica will behave like a transparent overlay that lets your clicks through to the windows below. 的當地語系化字串。
        /// </summary>
        internal static string MenuClickThroughTT {
            get {
                return ResourceManager.GetString("MenuClickThroughTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Close 的當地語系化字串。
        /// </summary>
        internal static string MenuClose {
            get {
                return ResourceManager.GetString("MenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Closes OnTopReplica. 的當地語系化字串。
        /// </summary>
        internal static string MenuCloseTT {
            get {
                return ResourceManager.GetString("MenuCloseTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 2:1 Double 的當地語系化字串。
        /// </summary>
        internal static string MenuFitDouble {
            get {
                return ResourceManager.GetString("MenuFitDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fullscreen 的當地語系化字串。
        /// </summary>
        internal static string MenuFitFullscreen {
            get {
                return ResourceManager.GetString("MenuFitFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1:2 Half 的當地語系化字串。
        /// </summary>
        internal static string MenuFitHalf {
            get {
                return ResourceManager.GetString("MenuFitHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1:1 Fit to window 的當地語系化字串。
        /// </summary>
        internal static string MenuFitOriginal {
            get {
                return ResourceManager.GetString("MenuFitOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1:4 Quarter 的當地語系化字串。
        /// </summary>
        internal static string MenuFitQuarter {
            get {
                return ResourceManager.GetString("MenuFitQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Group Switch mode 的當地語系化字串。
        /// </summary>
        internal static string MenuGroupSwitch {
            get {
                return ResourceManager.GetString("MenuGroupSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OnTopReplica will automatically clone a window from an user defined group, switching to the one least recently activated to the foreground. 的當地語系化字串。
        /// </summary>
        internal static string MenuGroupSwitchTT {
            get {
                return ResourceManager.GetString("MenuGroupSwitchTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 100% (opaque) 的當地語系化字串。
        /// </summary>
        internal static string MenuOp100 {
            get {
                return ResourceManager.GetString("MenuOp100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sets OnTopReplica to be completely opaque. 的當地語系化字串。
        /// </summary>
        internal static string MenuOp100TT {
            get {
                return ResourceManager.GetString("MenuOp100TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 25% 的當地語系化字串。
        /// </summary>
        internal static string MenuOp25 {
            get {
                return ResourceManager.GetString("MenuOp25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sets OnTopReplica to 25% opacity. 的當地語系化字串。
        /// </summary>
        internal static string MenuOp25TT {
            get {
                return ResourceManager.GetString("MenuOp25TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 50% 的當地語系化字串。
        /// </summary>
        internal static string MenuOp50 {
            get {
                return ResourceManager.GetString("MenuOp50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sets OnTopReplica to 50% opacity. 的當地語系化字串。
        /// </summary>
        internal static string MenuOp50TT {
            get {
                return ResourceManager.GetString("MenuOp50TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 75% 的當地語系化字串。
        /// </summary>
        internal static string MenuOp75 {
            get {
                return ResourceManager.GetString("MenuOp75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sets OnTopReplica to 75% opacity. 的當地語系化字串。
        /// </summary>
        internal static string MenuOp75TT {
            get {
                return ResourceManager.GetString("MenuOp75TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Opacity 的當地語系化字串。
        /// </summary>
        internal static string MenuOpacity {
            get {
                return ResourceManager.GetString("MenuOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open 的當地語系化字串。
        /// </summary>
        internal static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Displays OnTopReplica. 的當地語系化字串。
        /// </summary>
        internal static string MenuOpenTT {
            get {
                return ResourceManager.GetString("MenuOpenTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bottom Left 的當地語系化字串。
        /// </summary>
        internal static string MenuPosBottomLeft {
            get {
                return ResourceManager.GetString("MenuPosBottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bottom Right 的當地語系化字串。
        /// </summary>
        internal static string MenuPosBottomRight {
            get {
                return ResourceManager.GetString("MenuPosBottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Center 的當地語系化字串。
        /// </summary>
        internal static string MenuPosCenter {
            get {
                return ResourceManager.GetString("MenuPosCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Disabled 的當地語系化字串。
        /// </summary>
        internal static string MenuPosDisabled {
            get {
                return ResourceManager.GetString("MenuPosDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Position lock 的當地語系化字串。
        /// </summary>
        internal static string MenuPosition {
            get {
                return ResourceManager.GetString("MenuPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Automatically position OnTopReplica on the current screen. 的當地語系化字串。
        /// </summary>
        internal static string MenuPositionTT {
            get {
                return ResourceManager.GetString("MenuPositionTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Top Left 的當地語系化字串。
        /// </summary>
        internal static string MenuPosTopLeft {
            get {
                return ResourceManager.GetString("MenuPosTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Top Right 的當地語系化字串。
        /// </summary>
        internal static string MenuPosTopRight {
            get {
                return ResourceManager.GetString("MenuPosTopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Quit fullscreen mode 的當地語系化字串。
        /// </summary>
        internal static string MenuQuitFullscreen {
            get {
                return ResourceManager.GetString("MenuQuitFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Recall last position and size 的當地語系化字串。
        /// </summary>
        internal static string MenuRecall {
            get {
                return ResourceManager.GetString("MenuRecall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Toggles whether OnTopReplica should store its last position and size and use them when it is restarted. 的當地語系化字串。
        /// </summary>
        internal static string MenuRecallTT {
            get {
                return ResourceManager.GetString("MenuRecallTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Minimize 的當地語系化字串。
        /// </summary>
        internal static string MenuReduce {
            get {
                return ResourceManager.GetString("MenuReduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Minimizes OnTopReplica to the task bar (or the tray). 的當地語系化字串。
        /// </summary>
        internal static string MenuReduceTT {
            get {
                return ResourceManager.GetString("MenuReduceTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select region... 的當地語系化字串。
        /// </summary>
        internal static string MenuRegion {
            get {
                return ResourceManager.GetString("MenuRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Switches to &quot;region mode&quot;, that allows you to select a limited region of the source&apos;s window as thumbnail. 的當地語系化字串。
        /// </summary>
        internal static string MenuRegionTT {
            get {
                return ResourceManager.GetString("MenuRegionTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reset window 的當地語系化字串。
        /// </summary>
        internal static string MenuReset {
            get {
                return ResourceManager.GetString("MenuReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Resets OnTopReplica settings and its main window. 的當地語系化字串。
        /// </summary>
        internal static string MenuResetTT {
            get {
                return ResourceManager.GetString("MenuResetTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Resize 的當地語系化字串。
        /// </summary>
        internal static string MenuResize {
            get {
                return ResourceManager.GetString("MenuResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Restore last cloned window 的當地語系化字串。
        /// </summary>
        internal static string MenuRestoreLast {
            get {
                return ResourceManager.GetString("MenuRestoreLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 When enabled, OnTopReplica will attempt to restore the last cloned window on start up. 的當地語系化字串。
        /// </summary>
        internal static string MenuRestoreLastTT {
            get {
                return ResourceManager.GetString("MenuRestoreLastTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Settings... 的當地語系化字串。
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Displays the settings panel. 的當地語系化字串。
        /// </summary>
        internal static string MenuSettingsTT {
            get {
                return ResourceManager.GetString("MenuSettingsTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Switch to window 的當地語系化字串。
        /// </summary>
        internal static string MenuSwitch {
            get {
                return ResourceManager.GetString("MenuSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Switches to the source window and hides OnTopReplica. 的當地語系化字串。
        /// </summary>
        internal static string MenuSwitchTT {
            get {
                return ResourceManager.GetString("MenuSwitchTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select window 的當地語系化字串。
        /// </summary>
        internal static string MenuWindows {
            get {
                return ResourceManager.GetString("MenuWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 - none - 的當地語系化字串。
        /// </summary>
        internal static string MenuWindowsNone {
            get {
                return ResourceManager.GetString("MenuWindowsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Displays a list of window you can select as thumbnail source. 的當地語系化字串。
        /// </summary>
        internal static string MenuWindowsTT {
            get {
                return ResourceManager.GetString("MenuWindowsTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 - whole - 的當地語系化字串。
        /// </summary>
        internal static string MenuWindowsWholeRegion {
            get {
                return ResourceManager.GetString("MenuWindowsWholeRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bottom 的當地語系化字串。
        /// </summary>
        internal static string RegionsBottom {
            get {
                return ResourceManager.GetString("RegionsBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Current region: 的當地語系化字串。
        /// </summary>
        internal static string RegionsCurrentRegion {
            get {
                return ResourceManager.GetString("RegionsCurrentRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        internal static string RegionsDeleteButton {
            get {
                return ResourceManager.GetString("RegionsDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Done 的當地語系化字串。
        /// </summary>
        internal static string RegionsDoneButton {
            get {
                return ResourceManager.GetString("RegionsDoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Height 的當地語系化字串。
        /// </summary>
        internal static string RegionsHeight {
            get {
                return ResourceManager.GetString("RegionsHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Left 的當地語系化字串。
        /// </summary>
        internal static string RegionsLeft {
            get {
                return ResourceManager.GetString("RegionsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reset 的當地語系化字串。
        /// </summary>
        internal static string RegionsResetButton {
            get {
                return ResourceManager.GetString("RegionsResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Right 的當地語系化字串。
        /// </summary>
        internal static string RegionsRight {
            get {
                return ResourceManager.GetString("RegionsRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save 的當地語系化字串。
        /// </summary>
        internal static string RegionsSaveButton {
            get {
                return ResourceManager.GetString("RegionsSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Stored regions 的當地語系化字串。
        /// </summary>
        internal static string RegionsStoredRegions {
            get {
                return ResourceManager.GetString("RegionsStoredRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Regions: 的當地語系化字串。
        /// </summary>
        internal static string RegionsTitle {
            get {
                return ResourceManager.GetString("RegionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Top 的當地語系化字串。
        /// </summary>
        internal static string RegionsTop {
            get {
                return ResourceManager.GetString("RegionsTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Width 的當地語系化字串。
        /// </summary>
        internal static string RegionsWidth {
            get {
                return ResourceManager.GetString("RegionsWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 X 的當地語系化字串。
        /// </summary>
        internal static string RegionsX {
            get {
                return ResourceManager.GetString("RegionsX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Y 的當地語系化字串。
        /// </summary>
        internal static string RegionsY {
            get {
                return ResourceManager.GetString("RegionsY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Right-click here to start... 的當地語系化字串。
        /// </summary>
        internal static string RightClick {
            get {
                return ResourceManager.GetString("RightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clone current window 的當地語系化字串。
        /// </summary>
        internal static string SettingsHotKeyClone {
            get {
                return ResourceManager.GetString("SettingsHotKeyClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 These system-wide shortcuts can also be used when OnTopReplica is not in focus. 的當地語系化字串。
        /// </summary>
        internal static string SettingsHotKeyDescription {
            get {
                return ResourceManager.GetString("SettingsHotKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show/Hide 的當地語系化字串。
        /// </summary>
        internal static string SettingsHotKeyShowHide {
            get {
                return ResourceManager.GetString("SettingsHotKeyShowHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hot keys: 的當地語系化字串。
        /// </summary>
        internal static string SettingsHotKeyTitle {
            get {
                return ResourceManager.GetString("SettingsHotKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Language: 的當地語系化字串。
        /// </summary>
        internal static string SettingsLanguageTitle {
            get {
                return ResourceManager.GetString("SettingsLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Requires a restart. 的當地語系化字串。
        /// </summary>
        internal static string SettingsRestartRequired {
            get {
                return ResourceManager.GetString("SettingsRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Settings 的當地語系化字串。
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel update
        ///OnTopReplica will prompt you the next time it is started. 的當地語系化字串。
        /// </summary>
        internal static string UpdateAvailableCommandCancel {
            get {
                return ResourceManager.GetString("UpdateAvailableCommandCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Download
        ///Install OnTopReplica {0}. 的當地語系化字串。
        /// </summary>
        internal static string UpdateAvailableCommandOk {
            get {
                return ResourceManager.GetString("UpdateAvailableCommandOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The new version can be downloaded and installed from the official website. 的當地語系化字串。
        /// </summary>
        internal static string UpdateAvailableContent {
            get {
                return ResourceManager.GetString("UpdateAvailableContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Installed version: {0}
        ///Available version: {1} 的當地語系化字串。
        /// </summary>
        internal static string UpdateAvailableExpanded {
            get {
                return ResourceManager.GetString("UpdateAvailableExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Version {0} available 的當地語系化字串。
        /// </summary>
        internal static string UpdateAvailableInstruction {
            get {
                return ResourceManager.GetString("UpdateAvailableInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0}/{1} bytes downloaded. 的當地語系化字串。
        /// </summary>
        internal static string UpdateDownloadingContent {
            get {
                return ResourceManager.GetString("UpdateDownloadingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Downloading... 的當地語系化字串。
        /// </summary>
        internal static string UpdateDownloadingInstruction {
            get {
                return ResourceManager.GetString("UpdateDownloadingInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The latest version of OnTopReplica is already installed. The program automatically checks for updates at every start.
        ///
        ///You can keep up to date about OnTopReplica&apos;s development, suggest improvements and new features by &lt;a href=&quot;website&quot;&gt;visiting the official website&lt;/a&gt;. 的當地語系化字串。
        /// </summary>
        internal static string UpdateInfoContent {
            get {
                return ResourceManager.GetString("UpdateInfoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Latest stable version released on {0}. 的當地語系化字串。
        /// </summary>
        internal static string UpdateInfoFooter {
            get {
                return ResourceManager.GetString("UpdateInfoFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OnTopReplica is up to date 的當地語系化字串。
        /// </summary>
        internal static string UpdateInfoInstruction {
            get {
                return ResourceManager.GetString("UpdateInfoInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Install
        ///OnTopReplica will be closed and the update installed. 的當地語系化字串。
        /// </summary>
        internal static string UpdateReadyCommandOk {
            get {
                return ResourceManager.GetString("UpdateReadyCommandOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OnTopReplica version {0} is ready to be installed on your computer. 的當地語系化字串。
        /// </summary>
        internal static string UpdateReadyContent {
            get {
                return ResourceManager.GetString("UpdateReadyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update ready 的當地語系化字串。
        /// </summary>
        internal static string UpdateReadyInstruction {
            get {
                return ResourceManager.GetString("UpdateReadyInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OnTopReplica updates 的當地語系化字串。
        /// </summary>
        internal static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
    }
}
